config/routes.rb
Rails.application.routes.draw do


  get 'products/index', to: 'products#index', as: 'admindashboard'
  get 'products/new', to: 'products#new', as: 'new_product'
      #url pattern            #controller#action   #prefix 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'products', to: 'products#create'
  get 'products/:id',to: 'products#show', as: 'product' 
  get 'products/:id/edit', to: 'products#edit', as: 'edit_product'
  put '/products/:id', to: 'products#update'
  delete '/products/:id', to: 'products#destroy', as: 'delete_product'
  #resources :products  #, except: ['new','create']
  root 'products#index'


  ###product_category
  get 'products/:id/product_categories/new', to: 'product_categories#new', as: 'new_category'
  post'products/:id/product_categories', to: 'product_categories#create', as: 'categories'
  get 'products/:id/product_categories/index', to: 'product_categories#index', as: 'list_categories'
  get 'product_category/:id/edit', to: 'product_categories#edit', as: 'edit_product_category'
  put '/product_category/:id', to: 'product_categories#update',as: 'product_category'
  delete '/product_category/:id', to: 'product_categories#destroy', as: 'delete_product_category'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :product_categories, dependent: :destroy
    validates :product_name, presence: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
    def new
        @ProductCategory=ProductCategory.new
      end

      def create
        @product=Product.find(params[:id])
        @ProductCategory=@product.product_categories.new(category_params)
        if @ProductCategory.save
            redirect_to list_categories_path(@product)
        else
            render :new
        end
    #render plain: params.inspect    
      end

      def index
        #render plain: params.inspect
        @product=Product.find(params[:id])
      end


      def edit
        @product_category=ProductCategory.find(params[:id])
      end
    
      def update
        @product_category=ProductCategory.find(params[:id])
        render plain: params.inspect    
        if(@product_category.update(category_params))
          flash[:notice] = "record updated!!!!"
          redirect_to  list_categories_path
        else
          render :edit
        end
    
      end   
      def destroy
        @product_category=ProductCategory.find(params[:id])
        @product_category.destroy
        redirect_to  list_categories_path
      end
      private
      def category_params
        params.require(:ProductCategory).permit(:name,:price,:quantity,:description)
      end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products=Product.all
  end

  def new
    @product=Product.new
  end

  def create
    #render plain: params[:product].inspect
    @product=Product.new(product_params)
    if  @product.save
    flash[:notice] = "record created!!!!"
    redirect_to admindashboard_path
    else
      render :new
    end
  end

  def edit
    @product=Product.find(params[:id])
  end

  def update
    @product=Product.find(params[:id])
    if(@product.update(product_params))
      flash[:notice] = "record updated!!!!"
      redirect_to admindashboard_path
    else
      render :edit
    end

  end


  def show
    @product=Product.find(params[:id])
  end

  def destroy
    @product=Product.find(params[:id])
    @product.destroy
    redirect_to admindashboard_path
  end
  private
  def product_params
      params.require(:product).permit(:product_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

     <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product_categories/edit.html.erb
<%= form_for :product_category, url: product_category_path(@product_category), method: :put do |f| %>
  
    <% if @product_category.errors.any?%>
        <% @product_category.errors.full_messages.each do |msg| %>
            <%= msg %>
            <% end %>
    <% end %>
    <div class="well">
    Category Name <%= f.text_field :name %>
    Price <%= f.text_field :price %>
    Quantity<%= f.text_field :quantity %>
    Description<%= f.text_field :description %>
    <%= f.submit(:edit, {class: 'btn btn-primary'}) %>
    <%=link_to 'cancel', admindashboard_path, class: 'btn btn-primary'%>
    </div>
<% end %>

app/views/product_categories/index.html.erb
<h2><%= @product.product_name %></h2>
<%if @product.product_categories.empty?%>
    <p>No List Found</p>
<% else %>
        <% @product.product_categories.each do |c|%>
            <div class="well">
                <h3><%= c.name %></h3>
                <p>Price <%= c.price %></p>
                <p>Quantity <%= c.quantity %></p>
                <p>Description <%= c.description %></p>
                <p><%= link_to 'Edit', edit_product_category_path(c), class: 'btn btn-primary' %>
                <%= link_to 'Delete', delete_product_category_path(c),method: :delete, data: {confirm: 'Are You Sure?'}, class: 'btn btn-danger' %></p>
            </div>
        <% end %>
 <% end %>

app/views/product_categories/new.html.erb
<div class="well" >
<%= form_for :ProductCategory, url: categories_path do |f| %>

    <% if @ProductCategory.errors.any?%>
        <% @ProductCategory.errors.full_messages.each do |msg| %>
            <%= msg %>
            <% end %>
    <% end %>
    Category Name <%= f.text_field :name %>
    Price <%= f.text_field :price %>
    Quantity<%= f.text_field :quantity %>
    Description<%= f.text_field :description %>
    <%= f.submit(:save, {class: 'btn btn-primary'}) %>
    <%=link_to 'cancel', admindashboard_path, class: 'btn btn-primary'%>
<% end %>
</div>

app/views/products/edit.html.erb
<%= form_for :product, url: product_path(@product), method: :put do |f| %>

    <% if @product.errors.any?%>
        <% @product.errors.full_messages.each do |msg| %>
            <%= msg %>
            <% end %>
    <% end %>
    Product Name <%= f.text_field :product_name%>
    <%= f.submit(:edit, {class: 'btn btn-primary'}) %>
    <%=link_to 'cancel', admindashboard_path, class: 'btn btn-primary'%>
<% end %>

app/views/products/index.html.erb
<div class="row">
        <%= link_to 'New Product', new_product_path,class: 'btn btn-primary'%>
        <div class="product-body">
        <h1>Product</h1>
        <% @products.each do |p|%>
            <div class="well">
            <p><%= p.product_name %>
            <%= link_to 'Edit',edit_product_path(p), class: 'btn btn-primary' %>
            <%= link_to 'View',list_categories_path(p), class: 'btn btn-primary' %>
            <%= link_to 'Delete',delete_product_path(p),method: :delete, data: {confirm: 'Are You Sure?'}, class: 'btn btn-danger' %>
            </p>
            </div>
        <% end %>
        </div>
  </div>      

app/views/products/new.html.erb
<%= form_for :product, url: products_path do |f| %>

    <% if @product.errors.any?%>
        <% @product.errors.full_messages.each do |msg| %>
            <%= msg %>
            <% end %>
    <% end %>
    Product Name <%= f.text_field :product_name%>
    <%= f.submit(:save, {class: 'btn btn-primary'}) %>
    <%=link_to 'cancel', admindashboard_path, class: 'btn btn-primary'%>
<% end %>

app/views/products/show.html.erb
<%=@product.product_name%>